# Generated by Django 2.0.5 on 2018-07-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjPadrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('num_pavimentos', models.IntegerField()),
                ('padrao', models.IntegerField()),
            ],
        ),
    ]
