# Generated by Django 2.0.5 on 2018-07-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projpadrao',
            name='estado',
            field=models.CharField(default='CE', max_length=2),
            preserve_default=False,
        ),
    ]
