# Generated by Django 2.0.7 on 2018-08-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cublista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('padrao', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mes', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
